### ISSUE TITLE
removing disconnected clients

### ISSUE THREAD

**Issue by Mat2095** [RowanHarley/Slither-Server#18] opened 2016-07-31 15:46 UTC
The server crashes when broadcasting a message to a client that has already disconnected. It seems they are not actually removed from the clients-array.

```
node_modules\ws\lib\WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (node_modules\ws\lib\WebSocket.js:219:16)
    at send (index.js:191:16)
    at broadcast (index.js:197:9)
    at WebSocketServer.handleMessage (index.js:115:13)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (node_modules\ws\lib\WebSocket.js:848:10)
    at node_modules\ws\lib\Receiver.js:628:18
    at node_modules\ws\lib\Receiver.js:368:7
    at node_modules\ws\lib\PerMessageDeflate.js:249:5
```

**Comment by RowanHarley** [comment] 2016-07-31 16:04
I've been trying to fix this problem for the past 10 minute's. I've tryed adding the remove snake packet ("s") and `delete clients[conn.id]` but nothing seems to work. Maybe there's something missing?

**Comment by RowanHarley** [comment] 2016-07-31 18:18
@Mat2095 I'm trying to debug what message's are sent from the original server's but my way of debugging isn't great for this. How can I debug it using WireShark, etc?

**Comment by Mat2095** [comment] 2016-07-31 18:29
Try `splice` instead of `delete`.
If that doesn't work, try `if (client && client.readyState == WebSocket.OPEN) {` (or something similar).
If that doesn't work either, set `clients[conn.id].disconnected=true;` and later check `if (client && !client.disconnected) {` or something like that.
No, there are no messages missing. This problem is all about javascript/websocket.

**Comment by RowanHarley** [comment] 2016-08-01 07:50
I've tryed them all but they don't work. Maybe I'm missing a packet that must be sent when the snake dies?

**Comment by RowanHarley** [comment] 2016-08-01 08:09
Ok, so I realised that I was trying to start the wrong file (oops!). The snake now dies when it hits off the wall but it doesn't go to the home screen. Another problem I noticed is that the snake only dies when half it's body goes through. I think I know the source of that problem though

**Comment by Mat2095** [comment] 2016-08-01 13:33
No, because this also happened when the player just killed the connection (e.g. by reloading the page).
Also you are not missing any packet, because at this point the connection is closed, you CAN'T send any more packets.
The solution is (almost as I suggested):

``` javascript
function send (id, data) {
    var client = clients[id];
    if (client && client.readyState == client.OPEN) {
        var currentTime = Date.now();
        var deltaTime = client.lastTime ? currentTime - client.lastTime : 0;
        client.lastTime = currentTime;
        message.writeInt16(0, data, deltaTime);
        client.send(data, {binary: true});
    }
}
```

**Comment by Mat2095** [comment] 2016-08-01 13:36
For debugging I use this addon https://chrome.google.com/webstore/detail/resource-override/pkoacgokdfckfpndoffpifphamojphii to override the game-client and just print the information I want to the console.

**Comment by RowanHarley** [comment] 2016-08-11 10:25
Ok, I'm back from holidays and working on the project. When I add `if (client && client.readyState == client.OPEN) { }` the snake ends up moving no-where and spawns outside the map.

**Comment by Mat2095** [comment] 2016-08-11 12:54
But it doesn't crash any more, does it? :D

**Comment by RowanHarley** [comment] 2016-08-11 13:46
Didn't think it crashed before... :laughing:

**Comment by Mat2095** [comment] 2016-08-11 14:02
It did for me. lol?

**Comment by RowanHarley** [comment] 2016-08-11 14:19
Was that the newest version?

**Comment by Mat2095** [comment] 2016-08-11 15:52
The newest version 11 days ago

**Comment by RowanHarley** [comment] 2016-08-11 16:07
Just download the master branch. It's easier

**Comment by RowanHarley** [comment] 2016-08-11 16:07
btw, had a look at some of your apps. 1k downloads!

**Comment by Mat2095** [comment] 2016-08-11 20:48
Still crashing :(

```
PS C:\Users\Matthias\Desktop\Slither-Server-master\Slither-Server-master> node .\index.js
[DEBUG] You are currently running on 0.0.5b5
[SERVER] Starting Server...
[SERVER] Server Started at 127.0.0.1:8080! Waiting for Connections...
[BOTS] Bot Status:
[BOTS] Creating 0 bots!
[BOTS] Bots successfully loaded: 0
[BOTS] Reason: Bot's aren't implemented yet. Please try again later
[DEBUG] An unnamed snake has connected!
[DEBUG] Connection closed.
C:\Users\Matthias\Desktop\Slither-Server-master\Slither-Server-master\node_modules\ws\lib\WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (C:\Users\Matthias\Desktop\Slither-Server-master\Slither-Server-master\node_modules\ws\lib\WebSocket.js:219:16)
    at send (C:\Users\Matthias\Desktop\Slither-Server-master\Slither-Server-master\index.js:195:16)
    at broadcast (C:\Users\Matthias\Desktop\Slither-Server-master\Slither-Server-master\index.js:201:9)
    at WebSocketServer.handleMessage (C:\Users\Matthias\Desktop\Slither-Server-master\Slither-Server-master\index.js:115:13)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (C:\Users\Matthias\Desktop\Slither-Server-master\Slither-Server-master\node_modules\ws\lib\WebSocket.js:848:10)
    at C:\Users\Matthias\Desktop\Slither-Server-master\Slither-Server-master\node_modules\ws\lib\Receiver.js:628:18
    at C:\Users\Matthias\Desktop\Slither-Server-master\Slither-Server-master\node_modules\ws\lib\Receiver.js:368:7
    at C:\Users\Matthias\Desktop\Slither-Server-master\Slither-Server-master\node_modules\ws\lib\PerMessageDeflate.js:249:5
```

Steps to reproduce:
- start Server (freshly downloaded from your master branch)
- connect with original client
- press F5 to force-quit/reload
- connect again -> crash

**Comment by RowanHarley** [comment] 2016-08-15 16:22
I think the problem is that when the page is reloaded before the snake dies, the websocket end's up not closing and the snake is left in the array of players in the game. To stop this from happening, to die just run into the wall. In the meantime I will look for a fix to this problem. Sorry for taking so long, I was on holiday's so I couldn't reproduce the bug.

**Comment by RowanHarley** [comment] 2016-08-15 17:43
I've fixed the bug causing the server to crash but when I crash off the wall, my snake dies but the death screen doesn't show. Any idea's why? We must be missing something!

**Comment by Mat2095** [comment] 2016-08-15 18:34
This is how the death works as far as I understand:
- Server notices death
- Server sends "remove snake" for the dead snake
- Server sends "v" (game-over/death/victory) packet to player
- Server waits a few seconds
- Server closes connection

**Comment by RowanHarley** [comment] 2016-08-16 08:13
I'm guessing the server waits a few seconds to make sure the last messages have been recieved

**Comment by RowanHarley** [comment] 2016-08-16 08:23
Ok, I've finally found the reason why the deatch screen didn't appear! It was because I forgot to broadcast the array!

**Closed as completed by RowanHarley** 2016-08-16 08:23 UTC
